# Generated by Django 6.0.3 on 2026-03-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="product/photo",
                verbose_name="Изображение",
            ),
        ),
    ]
