# Generated by Django 6.0.3 on 2026-03-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_product_photo_product_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image",
            new_name="photo",
        ),
    ]
