# Generated by Django 6.0.3 on 2026-03-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_rename_image_product_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="view_counter",
            new_name="views_counter",
        ),
    ]
